name: CurrentIter Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wally packages
        run: sh scripts/install-packages.sh

      - name: Analyze
        run: sh scripts/analyze.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          selene src/

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check code style
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.20.0
          args: --check src/

  setup-foreman:
    name: Setup Foreman
    uses: Roblox/setup-foreman@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      github-api-url: "https://api.github.com"
      permissions:
        contents: write
        pull-requests: write
        issues: read
        packages: none

  lua-action:
    name: Lua Action
    uses: MilesChou/lua-action@v0.0.1
    permissions:
      contents: write
      pull-requests: write
      issues: read
      packages: none
